# Generated by Django 3.2.24 on 2024-08-16 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_admin', '0018_alter_sub_admindt_subadmin_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sub_admindt',
            name='subadmin_id',
            field=models.CharField(default='619fafb7', max_length=8, unique=True),
        ),
    ]
